apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendtheraphy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendtheraphy
  template:
    metadata:
      labels:
        app: backendtheraphy
    spec:
      containers:
        - name: backendtheraphy
          image: mundex/digitalholics3-deployment:50
          ports:
            - containerPort: 8080